# Generated by Django 5.0 on 2023-12-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_announcement_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='data',
        ),
    ]
