# Generated by Django 5.0 on 2023-12-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_announcement_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='data',
            new_name='date',
        ),
    ]
