# Generated by Django 5.0 on 2024-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='about',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus deleniti praesentium a porro ea unde ex laborum beatae nulla modi?'),
        ),
    ]
